# /home/yaoyao/Documents/myProjects/ROS2WithSPCK/src/simpack_control/msg/SimpackY.msg

# 当前仿真时间戳(秒)
float64 sim_time

# 直接写28个字段
float64 y_yw01
float64 y_yw02
float64 y_yw03
float64 y_yw04

float64 y_yaw01
float64 y_yaw02
float64 y_yaw03
float64 y_yaw04

float64 y_wl01
float64 y_wr01
float64 y_wl02
float64 y_wr02
float64 y_wl03
float64 y_wr03
float64 y_wl04
float64 y_wr04

float64 y_yt01
float64 y_yt02
float64 y_yawt01
float64 y_yawt02

float64 y_speeddiff_front_a
float64 y_speeddiff_front_b
float64 y_speeddiff_front_c
float64 y_speeddiff_front_d
float64 y_speeddiff_rear_a
float64 y_speeddiff_rear_b
float64 y_speeddiff_rear_c
float64 y_speeddiff_rear_d
