# /home/yaoyao/Documents/myProjects/ROS2WithSPCK/src/simpack_interfaces/msg/SimpackY.msg

# 当前仿真时间戳(秒)
float64 sim_time

# 76 个DoFs 字段 (原28个)
float64 y_spcktime

float64 y_cb_vx

float64 y_cb_x
float64 y_cb_y
float64 y_cb_z
float64 y_cb_roll
float64 y_cb_yaw
float64 y_cb_pitch

float64 y_w01_rotw
float64 y_w02_rotw
float64 y_w03_rotw
float64 y_w04_rotw
float64 y_w05_rotw
float64 y_w06_rotw
float64 y_w07_rotw
float64 y_w08_rotw

float64 y_f01_x
float64 y_f01_y
float64 y_f01_z
float64 y_f01_roll
float64 y_f01_yaw
float64 y_f01_pitch

float64 y_f02_x
float64 y_f02_y
float64 y_f02_z
float64 y_f02_roll
float64 y_f02_yaw
float64 y_f02_pitch

float64 y_ws01_x
float64 y_ws01_y
float64 y_ws01_z
float64 y_ws01_roll
float64 y_ws01_yaw
float64 y_ws01_pitch

float64 y_ws02_x
float64 y_ws02_y
float64 y_ws02_z
float64 y_ws02_roll
float64 y_ws02_yaw
float64 y_ws02_pitch

float64 y_ws03_x
float64 y_ws03_y
float64 y_ws03_z
float64 y_ws03_roll
float64 y_ws03_yaw
float64 y_ws03_pitch

float64 y_ws04_x
float64 y_ws04_y
float64 y_ws04_z
float64 y_ws04_roll
float64 y_ws04_yaw
float64 y_ws04_pitch

float64 y_w01_rota
float64 y_w02_rota
float64 y_w03_rota
float64 y_w04_rota
float64 y_w05_rota
float64 y_w06_rota
float64 y_w07_rota
float64 y_w08_rota

float64 y_bar01_pitch
float64 y_bar02_pitch
float64 y_bar03_pitch
float64 y_bar04_pitch
float64 y_bar05_pitch
float64 y_bar06_pitch
float64 y_bar07_pitch
float64 y_bar08_pitch

float64 y_ws01_vy
float64 y_ws02_vy
float64 y_ws03_vy
float64 y_ws04_vy

float64 y_ws01_vyaw
float64 y_ws02_vyaw
float64 y_ws03_vyaw
float64 y_ws04_vyaw



